// ก่อนจะลืมถาม - คลังคำพูด (spec ส่วน B)
// ทุกประโยค tokenized: {them} = คำเรียกเขา, {me} = คำแทนตัวผู้ใช้
// "คอนเทนต์คือโปรดักต์ ไม่ใช่ UI"

import type { Category, Phrase } from "./types";

export const CATEGORY_LABELS: Record<Category, string> = {
  opener: "บทเปิด",
  memory: "ความทรงจำ",
  person: "รู้จักเขาในฐานะคน",
  thanks: "ขอบคุณ",
  apology: "ขอโทษ · ขอขมา · ให้อภัย",
  love: "รักนะ",
  worries: "เรื่องที่เขาห่วง",
  practical: "เรื่องปฏิบัติ",
  light: "คำถามเบาๆ",
  oneway: "พูดข้างเดียว",
  recovery: "กู้สถานการณ์",
  closing: "ปิดด้วยความอบอุ่น",
};

export const PHRASES: Phrase[] = [
  // ---------- B1 บทเปิด ----------
  {
    id: "op-photo",
    category: "opener",
    stage: "open",
    fears: ["know", "regret"],
    text: "เจอรูปเก่าในลิ้นชัก มีคนที่{me}ไม่รู้จักเยอะเลย {them}ช่วยดูหน่อยว่าใครบ้าง",
    note: "ใช้ “ข้ออ้าง” เป็นสะพาน - เขาแค่ช่วยเราทำงานอย่างหนึ่ง",
  },
  {
    id: "op-curry",
    category: "opener",
    stage: "open",
    fears: ["know", "regret"],
    text: "{me}อยากทำแกงที่{them}เคยทำเป็น สอนหน่อยได้ไหม จะได้ทำต่อ",
  },
  {
    id: "op-album",
    category: "opener",
    stage: "open",
    fears: ["know"],
    text: "{me}กำลังทำอัลบั้มรูปครอบครัว ขาดตอน{them}ยังหนุ่มสาวอยู่เลย เล่าให้ฟังหน่อย",
  },
  {
    id: "op-record",
    category: "opener",
    stage: "open",
    fears: ["know", "regret"],
    text: "{me}อยากอัดเสียง{them}เล่าเรื่องเก่าๆ ไว้ เผื่อหลานโตมาจะได้ฟัง เปิดอัดได้ไหม",
  },
  {
    id: "op-game",
    category: "opener",
    stage: "open",
    text: "มีคนแนะนำเกมถามตอบมา ดูสนุกดี {them}ลองเล่นด้วยกันไหม",
  },
  {
    id: "op-soft-1",
    category: "opener",
    stage: "open",
    text: "{them} {me}มีเรื่องอยากถามเยอะเลย แต่ไม่รู้จะเริ่มยังไง ถามทีละข้อได้ไหม",
  },
  {
    id: "op-soft-2",
    category: "opener",
    stage: "open",
    text: "{them} {me}นึกได้ว่ามีเรื่องที่ไม่เคยถามเลย อยากถามไว้ก่อนลืม",
  },
  {
    id: "op-soft-3",
    category: "opener",
    stage: "open",
    text: "เราไม่ค่อยได้คุยกันแบบนี้เนอะ วันนี้ขอคุยยาวๆ หน่อยได้ไหม",
  },
  {
    id: "op-soft-4",
    category: "opener",
    stage: "open",
    fears: ["regret"],
    text: "{me}กลัวว่าวันนึงจะนึกเสียดายว่าไม่ได้ถาม เลยขอถามตอนนี้เลยนะ",
  },
  // ประโยค "ให้สิทธิ์ปฏิเสธ" - spec: ต้องพูดในนาทีแรก
  {
    id: "op-permit-1",
    category: "opener",
    stage: "open",
    text: "ถ้าไม่อยากตอบข้อไหน บอกได้เลยนะ {me}จะข้ามไป ไม่ถามซ้ำ",
    note: "ประโยคให้สิทธิ์ปฏิเสธ - พูดในนาทีแรกเสมอ ทำให้เขารู้สึกยังควบคุมได้",
  },
  {
    id: "op-permit-2",
    category: "opener",
    stage: "open",
    text: "เหนื่อยเมื่อไหร่บอกนะ เราหยุดได้ตลอด ไว้ค่อยคุยต่อวันหลัง",
    note: "ประโยคให้สิทธิ์ปฏิเสธ",
  },
  {
    id: "op-permit-3",
    category: "opener",
    stage: "open",
    text: "ไม่มีคำตอบถูกผิดนะ อยากตอบสั้นก็ได้",
    note: "ประโยคให้สิทธิ์ปฏิเสธ",
  },
  // ชวนไปกินข้าว
  {
    id: "op-meal-1",
    category: "opener",
    stage: "open",
    text: "วันเสาร์ว่างไหม ไปร้านเดิมกัน นานแล้วที่ไม่ได้ไปกันสองคน",
  },
  {
    id: "op-meal-2",
    category: "opener",
    stage: "open",
    text: "อยากกินอะไรที่สุดตอนนี้ {me}จะไปหามาให้",
  },
  {
    id: "op-meal-3",
    category: "opener",
    stage: "open",
    text: "ไปกินข้าวกัน แค่เราสองคน ไม่ต้องชวนใคร",
  },
  {
    id: "op-meal-4",
    category: "opener",
    stage: "open",
    text: "วันนี้{me}เอาข้าวที่{them}ชอบมา กินไปคุยไปนะ",
    note: "สำหรับตอนอยู่โรงพยาบาล",
  },

  // ---------- B2 ความทรงจำ ----------
  {
    id: "mem-age",
    category: "memory",
    stage: "light",
    fears: ["know"],
    text: "ตอน{them}อายุเท่า{me}ตอนนี้ {them}ทำอะไรอยู่",
  },
  {
    id: "mem-happiest",
    category: "memory",
    stage: "light",
    fears: ["know"],
    text: "วันที่มีความสุขที่สุดในชีวิต{them}คือวันไหน",
  },
  {
    id: "mem-firstmeet",
    category: "memory",
    stage: "light",
    fears: ["know"],
    text: "{them}เจอกับคนรักครั้งแรกยังไง เล่าแบบละเอียดเลยนะ",
  },
  {
    id: "mem-naughty",
    category: "memory",
    stage: "light",
    fears: ["know"],
    text: "ตอนเด็กๆ {them}ซนเรื่องอะไรมากที่สุด",
  },
  {
    id: "mem-proud",
    category: "memory",
    stage: "light",
    fears: ["know"],
    text: "{them}มีเรื่องอะไรที่ทำแล้วภูมิใจมาก แต่ไม่เคยเล่าให้ใครฟังไหม",
  },
  {
    id: "mem-born",
    category: "memory",
    stage: "light",
    fears: ["know", "love"],
    text: "ตอน{me}เกิด {them}รู้สึกยังไง",
  },
  {
    id: "mem-childhood",
    category: "memory",
    stage: "light",
    fears: ["know"],
    text: "{me}เป็นเด็กแบบไหน {them}เล่าหน่อยว่าจำอะไรได้บ้าง",
  },
  {
    id: "mem-place",
    category: "memory",
    stage: "light",
    fears: ["know"],
    text: "ในชีวิตนี้ ที่ไหนที่{them}ชอบที่สุด",
  },
  {
    id: "mem-song",
    category: "memory",
    stage: "light",
    fears: ["know"],
    text: "เพลงอะไรที่พอ{them}ได้ยินแล้วนึกถึงตอนหนุ่มสาว",
  },
  {
    id: "mem-miss",
    category: "memory",
    stage: "light",
    fears: ["know"],
    text: "มีใครที่{them}คิดถึงบ่อยๆ แต่ไม่ได้เจอนานแล้วไหม",
  },

  // ---------- B3 รู้จักเขาในฐานะคน ----------
  {
    id: "per-ifnot",
    category: "person",
    stage: "deep",
    fears: ["know"],
    text: "ถ้าไม่ได้มี{me} ไม่ได้เป็น{them} {them}อยากใช้ชีวิตแบบไหน",
  },
  {
    id: "per-dream",
    category: "person",
    stage: "deep",
    fears: ["know"],
    text: "{them}มีความฝันอะไรที่วางไว้กลางทางไหม",
  },
  {
    id: "per-fear",
    category: "person",
    stage: "deep",
    fears: ["know"],
    text: "{them}กลัวอะไรมากที่สุดในชีวิต",
  },
  {
    id: "per-misunderstood",
    category: "person",
    stage: "deep",
    fears: ["know"],
    text: "มีอะไรที่คนอื่นเข้าใจ{them}ผิดมาตลอดไหม",
  },
  {
    id: "per-regret",
    category: "person",
    stage: "deep",
    fears: ["know"],
    text: "ถ้าย้อนกลับไปได้ {them}อยากแก้เรื่องไหน",
  },
  {
    id: "per-burden",
    category: "person",
    stage: "deep",
    fears: ["know"],
    text: "เรื่องอะไรที่{them}แบกไว้คนเดียวมานาน",
  },
  {
    id: "per-define",
    category: "person",
    stage: "deep",
    fears: ["know"],
    text: "{them}นิยามตัวเองว่าเป็นคนแบบไหน",
  },
  {
    id: "per-worth",
    category: "person",
    stage: "deep",
    fears: ["know"],
    text: "อะไรที่ทำให้{them}รู้สึกว่าชีวิตนี้คุ้มแล้ว",
  },

  // ---------- B4 ขอบคุณ ----------
  {
    id: "th-rice",
    category: "thanks",
    stage: "deep",
    fears: ["love"],
    text: "{me}ไม่เคยบอกเลยนะ ว่าที่{them}ตื่นตีห้าทำข้าวให้ทุกวัน {me}จำได้ทุกวัน",
    note: "ยิ่งเจาะจง ยิ่งกระทบใจ - ปรับให้เป็นเรื่องจริงของคุณ",
  },
  {
    id: "th-school",
    category: "thanks",
    stage: "deep",
    fears: ["love"],
    text: "ที่{them}ไม่เคยพลาดงานโรงเรียน{me}สักครั้ง {me}รู้ว่า{them}ลางานมา",
  },
  {
    id: "th-fail",
    category: "thanks",
    stage: "deep",
    fears: ["love"],
    text: "วันที่{me}ล้มเหลวที่สุด {them}เป็นคนเดียวที่ไม่ถามอะไรเลย แค่ทำข้าวให้กิน {me}ไม่เคยลืม",
  },
  {
    id: "th-fromyou",
    category: "thanks",
    stage: "deep",
    fears: ["love"],
    text: "สิ่งที่{me}เป็นทุกวันนี้ มาจาก{them}เกือบทั้งหมด",
  },
  {
    id: "th-patient",
    category: "thanks",
    stage: "deep",
    fears: ["love"],
    text: "ขอบคุณที่อดทนกับ{me}ตอนที่{me}เป็นเด็กที่ยากมาก",
  },
  {
    id: "th-here",
    category: "thanks",
    stage: "deep",
    fears: ["love"],
    text: "ขอบคุณที่ยังอยู่ตรงนี้ ให้{me}ได้พูดคำนี้",
  },
  {
    id: "th-easy-1",
    category: "thanks",
    stage: "deep",
    fears: ["love"],
    text: "{them}ทำดีกับ{me}มากนะ {me}รู้",
    note: "เวอร์ชันพูดง่าย",
  },
  {
    id: "th-easy-2",
    category: "thanks",
    stage: "deep",
    fears: ["love"],
    text: "ถ้าไม่มี{them} {me}คงไม่มาถึงตรงนี้",
    note: "เวอร์ชันพูดง่าย",
  },

  // ---------- B5 ขอโทษ · ขอขมา · ให้อภัย ----------
  {
    id: "ap-sorry-1",
    category: "apology",
    stage: "deep",
    fears: ["anger"],
    text: "{me}ขอโทษเรื่องวันนั้นนะ {me}คิดถึงมันบ่อยมาก",
  },
  {
    id: "ap-sorry-2",
    category: "apology",
    stage: "deep",
    fears: ["anger"],
    text: "{me}พูดแรงกับ{them}ไปเยอะ ตอนนั้น{me}ยังไม่เข้าใจอะไรเลย",
  },
  {
    id: "ap-sorry-3",
    category: "apology",
    stage: "deep",
    fears: ["anger"],
    text: "{me}หายไปหลายปี ไม่ได้โทรหา {me}ขอโทษจริงๆ",
  },
  {
    id: "ap-sorry-4",
    category: "apology",
    stage: "deep",
    fears: ["anger"],
    text: "มีเรื่องที่{me}ทำให้{them}เสียใจ {them}อาจจะลืมไปแล้ว แต่{me}ยังจำได้",
  },
  // ขออโหสิกรรม ⭐
  {
    id: "ap-ahosi-1",
    category: "apology",
    stage: "deep",
    fears: ["anger"],
    text: "{me}ขอขมา ถ้าเคยล่วงเกิน{them} ทางกาย วาจา ใจ ทั้งที่ตั้งใจและไม่ตั้งใจ ขอ{them}อโหสิกรรมให้{me}ด้วยนะ",
    note: "⭐ ภาษาที่ผู้ใหญ่ไทยคุ้นเคย - พูดเรื่องนี้ได้โดยไม่ต้องเอ่ยถึงความตาย",
  },
  {
    id: "ap-ahosi-2",
    category: "apology",
    stage: "deep",
    fears: ["anger"],
    text: "และถ้า{them}เคยทำอะไรให้{me}เสียใจ {me}อโหสิให้หมดแล้วนะ ไม่ต้องห่วงอะไรทั้งนั้น",
    note: "⭐ ประโยคคู่กับข้อบน",
  },
  // ให้อภัย
  {
    id: "ap-forgive-1",
    category: "apology",
    stage: "deep",
    fears: ["anger"],
    text: "เรื่องเก่าๆ {me}ปล่อยไปหมดแล้วนะ ไม่ต้องคิดแล้ว",
  },
  {
    id: "ap-forgive-2",
    category: "apology",
    stage: "deep",
    fears: ["anger"],
    text: "{me}ไม่โกรธแล้วจริงๆ อยากให้{them}รู้ไว้",
  },
  {
    id: "ap-forgive-3",
    category: "apology",
    stage: "deep",
    fears: ["anger"],
    text: "{them}ทำดีที่สุดเท่าที่{them}ทำได้แล้ว {me}เข้าใจแล้ว",
  },
  {
    id: "ap-forgive-4",
    category: "apology",
    stage: "deep",
    fears: ["anger"],
    text: "{them}ไม่ต้องขอโทษ{me}หรอก แต่ถ้าอยากพูด {me}ฟังอยู่",
  },
  // ถามเขาบ้าง
  {
    id: "ap-ask-1",
    category: "apology",
    stage: "deep",
    fears: ["anger", "know"],
    text: "มีอะไรที่ยังค้างคาใจ{them}อยู่ไหม อยากให้{me}ทำอะไรให้",
  },
  {
    id: "ap-ask-2",
    category: "apology",
    stage: "deep",
    fears: ["anger", "know"],
    text: "มีใครที่{them}อยากเจอ หรืออยากคุยด้วยไหม {me}จะพาไปหรือโทรให้",
  },
  {
    id: "ap-ask-3",
    category: "apology",
    stage: "deep",
    fears: ["anger", "know"],
    text: "มีเรื่องไหนที่{them}อยากบอกใครสักคน แต่ไม่มีโอกาส",
  },

  // ---------- B6 รักนะ ----------
  {
    id: "lv-1a",
    category: "love",
    stage: "deep",
    fears: ["love"],
    text: "{me}อยู่ตรงนี้นะ",
    note: "ระดับ 1 - ยังไม่ต้องพูดคำว่า “รัก”",
  },
  {
    id: "lv-1b",
    category: "love",
    stage: "deep",
    fears: ["love"],
    text: "{them}คือคนสำคัญที่สุดของ{me}",
    note: "ระดับ 1",
  },
  {
    id: "lv-1c",
    category: "love",
    stage: "deep",
    fears: ["love"],
    text: "{me}โชคดีมากที่มี{them}",
    note: "ระดับ 1",
  },
  {
    id: "lv-2a",
    category: "love",
    stage: "deep",
    fears: ["love"],
    text: "{me}รัก{them}นะ",
    note: "ระดับ 2 - พูดสั้นๆ แล้วเงียบ ไม่ต้องอธิบายต่อ",
  },
  {
    id: "lv-2b",
    category: "love",
    stage: "deep",
    fears: ["love"],
    text: "รัก{them}นะ พูดไม่ค่อยเป็น แต่รักจริงๆ",
    note: "ระดับ 2",
  },
  {
    id: "lv-3a",
    category: "love",
    stage: "deep",
    fears: ["love"],
    text: "{me}รัก{them}มาตลอด แค่ไม่เคยพูด วันนี้อยากพูดให้ได้ยินสักครั้ง",
    note: "ระดับ 3",
  },
  {
    id: "lv-3b",
    category: "love",
    stage: "deep",
    fears: ["love"],
    text: "ทุกครั้งที่{me}มีความสุข {me}อยากโทรบอก{them}ก่อนเสมอ",
    note: "ระดับ 3",
  },
  {
    id: "lv-touch",
    category: "love",
    stage: "deep",
    fears: ["love"],
    text: "{them}รู้ใช่ไหม",
    note: "ถ้าพูดไม่ออก - จับมือเขาไว้ตอนพูด",
  },

  // ---------- B7 เรื่องที่เขาห่วง ----------
  {
    id: "wo-1",
    category: "worries",
    stage: "deep",
    fears: ["practical", "regret"],
    text: "มีอะไรที่{them}เป็นห่วงอยู่ไหม อยากให้{me}ช่วยจัดการอะไรบ้าง",
    note: "ถามด้วยน้ำเสียงปกติ เหมือนถามเรื่องทั่วไป",
  },
  {
    id: "wo-2",
    category: "worries",
    stage: "deep",
    fears: ["practical"],
    text: "ช่วงนี้{them}อยากให้เป็นยังไงมากที่สุด อยู่บ้าน หรืออยู่โรงพยาบาล",
  },
  {
    id: "wo-3",
    category: "worries",
    stage: "deep",
    fears: ["practical"],
    text: "ถ้าถึงตอนที่{them}บอกเราไม่ได้แล้ว อยากให้เราตัดสินใจยังไง",
  },
  {
    id: "wo-4",
    category: "worries",
    stage: "deep",
    fears: ["practical"],
    text: "อยากให้ใครอยู่ข้างๆ บ้าง",
  },
  {
    id: "wo-5",
    category: "worries",
    stage: "deep",
    text: "มีเพลง หรือบทสวด ที่{them}อยากได้ยินไหม",
  },
  {
    id: "wo-6",
    category: "worries",
    stage: "deep",
    fears: ["practical"],
    text: "มีอะไรที่{them}ไม่อยากให้เกิดขึ้นเลยไหม",
  },
  {
    id: "wo-7",
    category: "worries",
    stage: "deep",
    fears: ["regret"],
    text: "อยากให้เราจำ{them}ไว้ยังไง",
  },
  {
    id: "wo-8",
    category: "worries",
    stage: "deep",
    fears: ["regret"],
    text: "มีอะไรอยากบอกหลานไหม {me}จะอัดเสียงเก็บไว้ให้",
  },
  // บอกทาง / ให้เขาสบายใจ
  {
    id: "wo-peace-1",
    category: "worries",
    stage: "close",
    fears: ["regret"],
    text: "ไม่ต้องห่วงอะไรแล้วนะ ทางนี้{me}ดูแลได้",
    note: "บอกทาง - ให้เขาไปอย่างสงบ",
  },
  {
    id: "wo-peace-2",
    category: "worries",
    stage: "close",
    fears: ["regret"],
    text: "{them}ทำหน้าที่ครบแล้ว พักได้แล้วนะ",
    note: "บอกทาง",
  },
  {
    id: "wo-peace-3",
    category: "worries",
    stage: "close",
    fears: ["regret"],
    text: "{me}จะดูแลคนที่เหลือให้เอง {them}วางใจได้",
    note: "บอกทาง",
  },
  {
    id: "wo-peace-4",
    category: "worries",
    stage: "close",
    fears: ["regret"],
    text: "{them}ไม่ได้ทิ้งใครไว้นะ {them}ให้ทุกอย่างที่ให้ได้แล้ว",
    note: "บอกทาง",
  },

  // ---------- B8 เรื่องปฏิบัติ ----------
  {
    id: "pr-1",
    category: "practical",
    stage: "deep",
    fears: ["practical"],
    text: "เรื่องบ้าน เรื่องเงิน {them}อยากให้จัดการยังไง {me}อยากทำให้ถูกใจ{them}",
    note: "วิธีถามคือ “ขอคำแนะนำ” ไม่ใช่ “ขอข้อมูล”",
  },
  {
    id: "pr-2",
    category: "practical",
    stage: "deep",
    fears: ["practical"],
    text: "มีเอกสารอะไรเก็บไว้ที่ไหนบ้าง เดี๋ยว{me}จดไว้",
  },
  {
    id: "pr-3",
    category: "practical",
    stage: "deep",
    fears: ["practical"],
    text: "รหัสมือถือ หรือบัญชีธนาคาร บอกไว้หน่อยได้ไหม",
  },
  {
    id: "pr-4",
    category: "practical",
    stage: "deep",
    fears: ["practical"],
    text: "งานศพ {them}อยากให้เป็นแบบไหน เรียบง่ายหรือใหญ่",
  },
  {
    id: "pr-5",
    category: "practical",
    stage: "deep",
    fears: ["practical"],
    text: "วัดไหน พระองค์ไหน",
  },
  {
    id: "pr-6",
    category: "practical",
    stage: "deep",
    fears: ["practical"],
    text: "มีของชิ้นไหนที่{them}อยากให้ใครเป็นพิเศษไหม",
  },
  {
    id: "pr-7",
    category: "practical",
    stage: "deep",
    fears: ["practical"],
    text: "มีหนี้ หรือมีคนติดค้างอะไรกันอยู่ไหม",
  },

  // ---------- B9 คำถามเบาๆ สำรอง ----------
  {
    id: "li-1",
    category: "light",
    stage: "light",
    text: "วันนี้อยากกินอะไร",
    note: "ตอบด้วยคำเดียวได้ - ใช้ตอนเขาเหนื่อย",
  },
  { id: "li-2", category: "light", stage: "light", text: "หนาวไหม เอาผ้าห่มไหม" },
  { id: "li-3", category: "light", stage: "light", text: "อยากฟังเพลงอะไร" },
  {
    id: "li-4",
    category: "light",
    stage: "light",
    text: "จำร้านก๋วยเตี๋ยวหน้าปากซอยได้ไหม",
  },
  { id: "li-5", category: "light", stage: "light", text: "ชอบหน้าฝนหรือหน้าหนาว" },
  {
    id: "li-6",
    category: "light",
    stage: "light",
    text: "หมาตัวแรกที่บ้านชื่ออะไรนะ",
  },
  {
    id: "li-7",
    category: "light",
    stage: "light",
    text: "อยากให้{me}อยู่เป็นเพื่อนเฉยๆ ไหม ไม่ต้องคุยก็ได้",
  },

  // ---------- B10 พูดข้างเดียว (เมื่อสื่อสารไม่ได้แล้ว) ----------
  {
    id: "ow-1",
    category: "oneway",
    stage: "deep",
    text: "{them} {me}มาแล้วนะ นั่งอยู่ข้างๆ นี่แหละ",
    note: "การได้ยินเป็นประสาทสัมผัสสุดท้ายที่หายไป",
  },
  {
    id: "ow-2",
    category: "oneway",
    stage: "deep",
    text: "ไม่ต้องพูดอะไรนะ {me}พูดเอง {them}ฟังอย่างเดียวพอ",
  },
  {
    id: "ow-3",
    category: "oneway",
    stage: "deep",
    text: "วันนี้ที่บ้าน…",
    note: "เล่าเรื่องธรรมดาๆ ของวันนี้ให้เขาฟัง",
  },
  {
    id: "ow-4",
    category: "oneway",
    stage: "deep",
    fears: ["love"],
    text: "{me}รัก{them}นะ พูดกี่ครั้งก็ไม่พอ",
  },
  {
    id: "ow-5",
    category: "oneway",
    stage: "deep",
    fears: ["anger"],
    text: "{me}ขอขมา ถ้าเคยล่วงเกิน{them}ไว้ ขออโหสิกรรมนะ",
  },
  {
    id: "ow-6",
    category: "oneway",
    stage: "deep",
    fears: ["regret"],
    text: "ไม่ต้องห่วงใครแล้วนะ ทุกคนสบายดี",
  },
  {
    id: "ow-7",
    category: "oneway",
    stage: "deep",
    fears: ["regret"],
    text: "{them}พักได้แล้วนะ {me}โอเค",
  },
  { id: "ow-8", category: "oneway", stage: "deep", text: "เดี๋ยว{me}มาใหม่พรุ่งนี้" },

  // ---------- B11 กู้สถานการณ์ ----------
  {
    id: "rc-1",
    category: "recovery",
    stage: "deep",
    text: "เอ๊ะ หนักไปละ เอาใหม่ ถามเรื่องเบาๆ ดีกว่า",
    note: "เมื่อบรรยากาศหนักเกินไป",
  },
  {
    id: "rc-2",
    category: "recovery",
    stage: "deep",
    text: "พักก่อนไหม กินน้ำก่อน",
    note: "เมื่อบรรยากาศหนักเกินไป",
  },
  {
    id: "rc-3",
    category: "recovery",
    stage: "deep",
    text: "ไม่เป็นไร ร้องไห้ก็ได้ นั่งเฉยๆ ด้วยกันก่อนก็ได้",
    note: "เมื่อบรรยากาศหนักเกินไป",
  },
  {
    id: "rc-4",
    category: "recovery",
    stage: "deep",
    text: "ไม่ต้องตกใจนะ {me}แค่รัก{them}มาก",
    note: "เมื่อคุณเองร้องไห้ - พูดได้ทั้งน้ำตา",
  },
  {
    id: "rc-5",
    category: "recovery",
    stage: "deep",
    text: "เดี๋ยวๆ ขอแป๊บนึง",
    note: "เมื่อคุณเองร้องไห้",
  },
  {
    id: "rc-6",
    category: "recovery",
    stage: "deep",
    text: "ไม่เป็นไรเลย ไว้ค่อยคุยก็ได้ วันนี้แค่มานั่งด้วย",
    note: "เมื่อเขาปฏิเสธ - อย่ากดดัน อย่าถามซ้ำในวันเดียวกัน",
  },
  {
    id: "rc-7",
    category: "recovery",
    stage: "deep",
    text: "โอเค งั้นไม่ถามแล้ว ดูทีวีด้วยกันไหม",
    note: "เมื่อเขาปฏิเสธ",
  },
  {
    id: "rc-8",
    category: "recovery",
    stage: "deep",
    text: "ไม่ได้จะพูดเรื่องนั้นเลย แค่นึกอยากบอกเฉยๆ",
    note: "เมื่อเขาพูดว่า “ไม่ต้องพูดแบบนี้ ยังไม่ตายหรอก”",
  },
  {
    id: "rc-9",
    category: "recovery",
    stage: "deep",
    text: "{me}แค่ไม่อยากรอให้ถึงวันที่เสียดาย",
    note: "เมื่อเขาพูดว่า “ยังไม่ตายหรอก”",
  },

  // ---------- B11 ปิดท้าย (ห้ามจบด้วยเรื่องหนัก) ----------
  {
    id: "cl-1",
    category: "closing",
    stage: "close",
    text: "ขอบคุณที่เล่าให้ฟังนะ วันนี้{me}มีความสุขมาก",
  },
  {
    id: "cl-2",
    category: "closing",
    stage: "close",
    text: "ไว้มาใหม่นะ มีเรื่องอยากถามอีกเยอะเลย",
  },
  {
    id: "cl-3",
    category: "closing",
    stage: "close",
    fears: ["love"],
    text: "รักนะ นอนหลับฝันดี",
  },
];

// Prompt สำหรับหน้า Letter (spec B12)
export const LETTER_PROMPTS: string[] = [
  "สิ่งที่ฉันอยากบอกคุณที่สุดคือ…",
  "สิ่งที่ฉันเสียใจที่ไม่ได้พูดคือ…",
  "ถ้าคุณยังอยู่ ฉันจะถามว่า…",
  "ฉันอยากให้คุณรู้ว่าตอนนี้ฉัน…",
  "ฉันขอโทษเรื่อง…",
  "ฉันให้อภัยคุณเรื่อง…",
];
